services:
    mysql:
        image: mysql
        ports:
          - "3306:3306"
        expose:
          - "3306"
        environment:
          - MYSQL_USER=desafiopicpay
          - MYSQL_PASSWORD=123456
          - MYSQL_DATABASE=desafiopicpay
          - MYSQL_ROOT_PASSWORD=123456
        volumes:
          - db_data:/var/lib/mysql

volumes:
  db_data: